title: UNH Cucurbit Program Documentation
description: Documention for the UNH cucurbit breeding program
theme: just-the-docs

url: https://unh-cucurbits.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
